# Generated by Django 4.2.5 on 2023-10-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_bookingevent_contactus_delete_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
