# Generated by Django 4.2.5 on 2023-10-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newsletter',
            new_name='NewsletterSubscriber',
        ),
    ]
